export const trainingGuideMarkdown = [
  "# Training Plan Guide",
  "",
  "## Description rule",
  "- `description` is the canonical human-facing workout body.",
  "- A user must be able to execute the workout from `description` alone.",
  "- `execution` is structured machine-facing data that mirrors the description — include it whenever the workout can be represented precisely with the supported block + alert model. It drives Apple Watch `.workout` file export, structured rendering, and analytics. If a workout cannot be represented cleanly, leave `execution` null rather than invent unsupported fields.",
  "- Do **not** put critical instructions exclusively in `execution` or `metadata`.",
  "",
  "## Apple Watch export (important)",
  "- `execution.appleWatch` is what enables the athlete to download a `.workout` file and send it to their Apple Watch for guided execution.",
  "- **Always set `appleWatch.activityType`** when the workout has a recognisable sport. Allowed values: `running`, `walking`, `cycling`, `swimming`, `hiking`, `functional-strength-training`, `other`.",
  "- **Always set `appleWatch.location`** when you know it: `outdoor` for road/trail/open water, `indoor` for treadmill/trainer/pool.",
  "- Without `execution` the download button is hidden entirely. With `execution` but no `appleWatch`, the file exports as generic 'other' activity and the watch shows no sport-specific metrics or alerts — fill in `appleWatch` whenever you know the sport.",
  "",
  "## Description format (suggested)",
  "",
  "Descriptions are rendered as markdown. Consistent structure helps athletes scan workouts quickly — especially poolside or mid-ride. This is a suggested format, not a strict requirement. Adapt to what makes sense for the workout.",
  "",
  "**General principles:**",
  "- Keep it scannable. Prefer short lines and bullets over dense paragraphs.",
  "- One concern per line — don't mix zone targets, nutrition reminders, and technique cues in the same sentence.",
  "",
  "**Suggested layout:**",
  "",
  "| Section | When to include | Format |",
  "|---|---|---|",
  "| Opening line | Always (except rest days) | 1–2 sentences: purpose + key constraint |",
  "| Focus cues | When there are non-structural reminders (nutrition, technique, gear) | Bulleted list under **Focus** bold heading |",
  "| Structure | When there are distinct segments (warmup/main/cooldown, intervals, sets) | Bulleted steps under `## Structure` heading, preceded by `---` |",
  "",
  "**Structure formatting rules:**",
  "- Always use bullet points for steps, even for flat sequences.",
  "- Precede the `## Structure` heading with `---` for a visual separator.",
  "- For repeated blocks, use `N reps of:` followed by nested bullets.",
  "",
  "**Example — interval run:**",
  "",
  "Your one quality run session per week — preserves lactate threshold for the fall half marathon.",
  "",
  "---",
  "",
  "## Structure",
  "- 2 km warmup at conversational pace (no faster than 6:20/km)",
  "- 4 km at 5:00/km (4:50–5:10/km)",
  "- 2 km cooldown at conversational pace (or slower!)",
  "",
  "**Example — steady endurance ride (no Structure needed — single zone):**",
  "",
  "Build distance, not intensity. Flat route preferred.",
  "",
  "**Focus**",
  "- Practice drinking from bottle every 20 min",
  "- If aero bars have arrived, try 3× 5-min blocks in aero — comfort over speed",
  "",
  "Z2 cycling throughout (HR 131–162, ~21–22 km/h)",
  "",
  "**Example — structured swim with reps:**",
  "",
  "Technique focus this week: relaxed kick from hips and front quadrant timing.",
  "",
  "**Focus**",
  "- Loose ankles — don't point toes hard (calf cramp risk)",
  "- Breathing: every 2 strokes on comfortable side during main sets, bilateral during warmup/cooldown only",
  "- Hydrate well before — you'll likely come from Marek again",
  "",
  "---",
  "",
  "## Structure",
  "- 200 m warmup (mix strokes, try bilateral breathing — low effort)",
  "",
  "4 reps of:",
  "- 25 m catch-up drill (one hand waits in front until the other joins — exaggerates the reach)",
  "- Brief rest at wall",
  "",
  "4 reps of:",
  "- 50 m freestyle @ comfortable",
  "- 20 s rest",
  "- Focus: reach fully forward before starting the pull, kick from hips with loose ankles",
  "",
  "3 reps of:",
  "- 100 m freestyle @ steady (breathe every 2)",
  "- 30 s rest",
  "- Focus: front quadrant timing — always one arm extended in front",
  "",
  "- 100 m breaststroke cooldown",
  "",
  "IF CRAMP: pull toes toward shin at the wall for 10 s, then continue",
  "",
  "**Simple workouts (rest, recovery, notes):** Skip section headings. A single sentence or two is fine.",
  "",
  "## Labels",
  "- Every workout should point to exactly one primary `label`.",
  "- Labels are the main classification system for workouts.",
  "- Prefer lowercase label keys.",
  "- Use hyphenated multi-word keys like `easy-run`, `open-water-swim`, `long-ride`, `race-pace`.",
  "- Labels may include flexible `metadata`, but core matching behavior belongs in `activitySports`.",
  "",
  "## activitySports guidance",
  "- `activitySports` defines which imported Strava activity sport types may automatically match a label.",
  "- A label may have zero, one, or many `activitySports`.",
  "- If imported activity matching matters, set `activitySports` explicitly.",
  "- Good examples:",
  "  - `easy-run` -> `Run`, `TrailRun`, `VirtualRun`",
  "  - `long-ride` -> `Ride`, `GravelRide`",
  "  - `mobility` -> []",
  "",
  "## Mermaid guidance",
  "- Trainer notes and plan notes may include mermaid code blocks.",
  "- Use `xychart-beta` bar charts for distributions and line charts for trends.",
  "- Do **not** use pie charts.",
  "",
  "## Icons",
  "Three icon formats are supported (in order of preference):",
  "1. **Tabler icon name** — a plain string like `run` or `bike`. This is the preferred format. Use `search_icons` to discover available names.",
  "2. **Emoji** — a single emoji character like 🏃 or 🏊",
  "3. **Raw SVG** — a string starting with `<svg` (rendered inline as-is)",
  "",
  "Common Tabler icon suggestions:",
  "- `run` — running",
  "- `bike` — cycling",
  "- `swimming` — swimming",
  "- `barbell` — weight training",
  "- `yoga` — yoga / flexibility",
  "- `stretching` — mobility / stretching",
  "- `walk` — walking",
  "- `trekking` — trail running / hiking",
  "- `trophy` — race day / competitions",
  "- `bed` — rest / recovery",
  "- `heartbeat` — heart rate / cardio",
  "- `bolt` — speed / power",
  "",
  "## Metadata shapes",
  "",
  "### workout metadata",
  "```ts",
  "{",
  "  optional?: boolean,",
  "  ui?: {",
  "    variant?: 'standard' | 'rest' | 'note'",
  "  },",
  "  intervals?: Array<...>,",
  "  zones?: Array<...>,",
  "  sets?: Array<...>,",
  "  segments?: Array<...>,",
  "  [key: string]: unknown",
  "}",
  "```",
  "",
  "### execution",
  "The full schema for `execution` lives on the `add_workouts` / `update_workout` tool inputs. This guide covers conventions and examples; the tool input schema is authoritative.",
  "- **Use version 2** — set `version: 2`.",
  "- **Use `alert`, not `cue`** — the legacy cue object is no longer accepted.",
  "- Supported block types: `warmup`, `cooldown`, `steady`, `rest`, `free`, `interval`, `repeat`.",
  "- Unsupported in `execution`: `strength`, `note`, `lap-button`, `poolLengthMeters`, `displayHints`, and `appleWatch.alerts`.",
  "",
  "```ts",
  "{",
  "  version: 2,",
  "  structure: [",
  "    { type: 'warmup', target: { type: 'time', seconds: 600 } },",
  "    {",
  "      type: 'interval',",
  "      repetitions: 4,",
  "      work: {",
  "        target: { type: 'distance', meters: 1000 },",
  "        alert: { type: 'paceRange', unit: 'min/km', min: '4:50', max: '5:10' }",
  "      },",
  "      recovery: { target: { type: 'time', seconds: 90 } }",
  "    },",
  "    { type: 'cooldown', target: { type: 'time', seconds: 300 } }",
  "  ],",
  "  appleWatch: { activityType: 'running', location: 'outdoor' }",
  "}",
  "```",
  "",
  "## Conventions",
  '- **Pace** — use `M:SS` strings for `min/km` and `min/mi` (e.g. `"4:50"`); use positive numbers for `km/h` and `mph`. Use `paceRange` for bounded targets and `paceThreshold` for one-sided / single-value targets. For time-based pace ranges, `min` is the faster bound and `max` is the slower bound.',
  '- **Heart rate** — use exactly one alert per step. Prefer `heartRateZone` (`{ type: "heartRateZone", zone: 2 }`). Use `heartRateRange` only for bespoke BPM windows (`{ type: "heartRateRange", min: 131, max: 162 }`).',
  "- **Single alert per step** — do not combine pace + heart rate + power + cadence on the same step. Pick the one most important watch alert for that phase.",
].join("\n");
