export const trainingGuideMarkdown = [
  "# Training Plan Guide",
  "",
  "## Agent memory",
  "- Each plan has an `agentMemory` field: a freeform markdown notepad **scoped to that one plan**. It is returned by `get_plan` (as `agent_memory`).",
  "- Read it at the start of a session and keep it updated with durable, plan-specific context you'd otherwise lose between sessions: pace/HR zones, the athlete's plan-relevant constraints and preferences, and reminders to yourself about future changes to this plan.",
  "- **It is a notepad, not a memory store.** Only keep things that concern *this plan*. User-specific or cross-plan information belongs in your own memory, not here.",
  "- **Edit it with `edit_plan_memory`** (not `update_plan`):",
  "  - `op: 'replace'` — change a section (exact `oldText` → `newText`), delete one (`newText: ''`), or rewrite the whole document (`oldText` = the entire current content).",
  "  - `op: 'append'` — add to the end; also how you set the first note on an empty plan. `create_plan` can seed initial content too.",
  "- **Staleness is enforced by exact match.** `oldText` must match the current content verbatim, and the write only lands if the memory hasn't changed since you read it. A refused edit (`CONFLICT`) means: call `get_plan` to re-read, then retry against the latest content. Curate as you go — prune stale notes rather than appending endlessly.",
  "- It is private to the athlete: it is **not** included in public plan shares.",
  "- It is markdown and may include `chart` code blocks (e.g. a zone table).",
  "- This is distinct from plan notes (`add_plan_note`): notes are a dated, append-only log; agent memory is a single, living document.",
  "",
  "## Description rule",
  "- `description` is the canonical human-facing workout body.",
  "- A user must be able to execute the workout from `description` alone.",
  "- `execution` is structured machine-facing data that mirrors the description — include it whenever the workout can be represented precisely with the supported block + alert model. It drives Apple Watch `.workout` file export, structured rendering, and analytics. If a workout cannot be represented cleanly, leave `execution` null rather than invent unsupported fields.",
  "- Do **not** put critical instructions exclusively in `execution` or `metadata`.",
  "",
  "## Apple Watch export (important)",
  "- `execution.appleWatch` is what enables the athlete to download a `.workout` file and send it to their Apple Watch for guided execution.",
  "- **Always set `appleWatch.activityType`** when the workout has a recognisable sport. Allowed values: `running`, `walking`, `cycling`, `swimming`, `hiking`, `functional-strength-training`, `other`.",
  "- **Always set `appleWatch.location`** when you know it: `outdoor` for road/trail/open water, `indoor` for treadmill/trainer/pool.",
  "- Without `execution` the download button is hidden entirely. With `execution` but no `appleWatch`, the file exports as generic 'other' activity and the watch shows no sport-specific metrics or alerts — fill in `appleWatch` whenever you know the sport.",
  "",
  "## Description format (suggested)",
  "",
  "Descriptions are rendered as markdown. Consistent structure helps athletes scan workouts quickly — especially poolside or mid-ride. This is a suggested format, not a strict requirement. Adapt to what makes sense for the workout.",
  "",
  "**General principles:**",
  "- Keep it scannable. Prefer short lines and bullets over dense paragraphs.",
  "- One concern per line — don't mix zone targets, nutrition reminders, and technique cues in the same sentence.",
  "",
  "**Suggested layout:**",
  "",
  "| Section | When to include | Format |",
  "|---|---|---|",
  "| Opening line | Always (except rest days) | 1–2 sentences: purpose + key constraint |",
  "| Focus cues | When there are non-structural reminders (nutrition, technique, gear) | Bulleted list under **Focus** bold heading |",
  "| Structure | When there are distinct segments (warmup/main/cooldown, intervals, sets) | Bulleted steps under `## Structure` heading, preceded by `---` |",
  "",
  "**Structure formatting rules:**",
  "- Always use bullet points for steps, even for flat sequences.",
  "- Precede the `## Structure` heading with `---` for a visual separator.",
  "- For repeated blocks, use `N reps of:` followed by nested bullets.",
  "",
  "**Example — interval run:**",
  "",
  "Your one quality run session per week — preserves lactate threshold for the fall half marathon.",
  "",
  "---",
  "",
  "## Structure",
  "- 2 km warmup at conversational pace (no faster than 6:20/km)",
  "- 4 km at 5:00/km (4:50–5:10/km)",
  "- 2 km cooldown at conversational pace (or slower!)",
  "",
  "**Example — steady endurance ride (no Structure needed — single zone):**",
  "",
  "Build distance, not intensity. Flat route preferred.",
  "",
  "**Focus**",
  "- Practice drinking from bottle every 20 min",
  "- If aero bars have arrived, try 3× 5-min blocks in aero — comfort over speed",
  "",
  "Z2 cycling throughout (HR 131–162, ~21–22 km/h)",
  "",
  "**Example — structured swim with reps:**",
  "",
  "Technique focus this week: relaxed kick from hips and front quadrant timing.",
  "",
  "**Focus**",
  "- Loose ankles — don't point toes hard (calf cramp risk)",
  "- Breathing: every 2 strokes on comfortable side during main sets, bilateral during warmup/cooldown only",
  "- Hydrate well before — you'll likely come from Marek again",
  "",
  "---",
  "",
  "## Structure",
  "- 200 m warmup (mix strokes, try bilateral breathing — low effort)",
  "",
  "4 reps of:",
  "- 25 m catch-up drill (one hand waits in front until the other joins — exaggerates the reach)",
  "- Brief rest at wall",
  "",
  "4 reps of:",
  "- 50 m freestyle @ comfortable",
  "- 20 s rest",
  "- Focus: reach fully forward before starting the pull, kick from hips with loose ankles",
  "",
  "3 reps of:",
  "- 100 m freestyle @ steady (breathe every 2)",
  "- 30 s rest",
  "- Focus: front quadrant timing — always one arm extended in front",
  "",
  "- 100 m breaststroke cooldown",
  "",
  "IF CRAMP: pull toes toward shin at the wall for 10 s, then continue",
  "",
  "**Simple workouts (rest, recovery, notes):** Skip section headings. A single sentence or two is fine.",
  "",
  "## Labels",
  "- Every workout should point to exactly one primary `label`.",
  "- Labels are the main classification system for workouts.",
  "- Prefer lowercase label keys.",
  "- Use hyphenated multi-word keys like `easy-run`, `open-water-swim`, `long-ride`, `race-pace`.",
  "- Labels may include flexible `metadata`, but core matching behavior belongs in `activitySports`.",
  "",
  "## activitySports guidance",
  "- `activitySports` defines which imported Strava activity sport types may automatically match a label.",
  "- A label may have zero, one, or many `activitySports`.",
  "- If imported activity matching matters, set `activitySports` explicitly.",
  "- Good examples:",
  "  - `easy-run` -> `Run`, `TrailRun`, `VirtualRun`",
  "  - `long-ride` -> `Ride`, `GravelRide`",
  "  - `mobility` -> []",
  "",
  "## Chart guidance",
  "- Trainer notes, plan notes, and workout descriptions may include `chart` code blocks.",
  "- The renderer uses **Recharts** under the hood — props you'd recognise from Recharts (`dataKey`, `yAxisId`, `domain`, `referenceArea`, `referenceLine`, multi-axis composed charts) work the same way through this JSON shape.",
  "- Do **not** emit `mermaid` code blocks; mermaid support has been removed.",
  "",
  "### Block format",
  "A chart is a fenced code block tagged `chart` containing JSON. The top-level `type` selects the chart variant:",
  "- `bar`, `line`, `area`, `composed`, `scatter`, `radar`, `radial-bar`.",
  "",
  "### Data shape",
  "`data` is a flat array of records. Series reference fields by `dataKey`:",
  "",
  "```json",
  "{",
  '  "type": "bar",',
  '  "title": "Zone Distribution",',
  '  "data": [',
  '    { "zone": "Z1", "minutes": 145 },',
  '    { "zone": "Z2", "minutes": 230 },',
  '    { "zone": "Z3", "minutes": 65 },',
  '    { "zone": "Z4", "minutes": 30 },',
  '    { "zone": "Z5", "minutes": 12 }',
  "  ],",
  '  "xAxis": { "dataKey": "zone" },',
  '  "yAxis": { "label": "min" },',
  '  "series": [{ "dataKey": "minutes", "hue": 145, "name": "Time in zone" }]',
  "}",
  "```",
  "",
  "### Colors — hue only",
  "- Each series accepts a `hue` (number 0–360). The renderer expands it via OKLCH recipes that adapt across dark/light themes — agents do **not** pass raw colors, hex codes, or CSS variables.",
  '- Optional `tone: "accent" | "tint"` overrides the per-series-type default (accent for line/bar, tint for area fills).',
  "- Omit `hue` to fall back to a deterministic hash from the series `dataKey`.",
  "- Reference areas / lines also accept `hue` if you want them tinted; otherwise reference lines render in the muted-text color.",
  "",
  "### Multi-axis & composed",
  "Use `composed` with mixed `series[].type` for bar+line / area+line overlays. For dual-axis, supply `yAxis` as an array and reference each via `series[].yAxisId`:",
  "",
  "```json",
  "{",
  '  "type": "composed",',
  '  "data": [{ "km": 0, "hr": 132, "elev": 120 }],',
  '  "xAxis": { "dataKey": "km", "label": "km" },',
  '  "yAxis": [',
  '    { "id": "hr", "label": "HR", "domain": [120, 175], "orientation": "left" },',
  '    { "id": "elev", "label": "Elev", "orientation": "right" }',
  "  ],",
  '  "series": [',
  '    { "type": "area", "dataKey": "elev", "yAxisId": "elev", "hue": 200 },',
  '    { "type": "line", "dataKey": "hr",   "yAxisId": "hr",   "hue": 25 }',
  "  ],",
  '  "referenceAreas": [{ "yAxisId": "hr", "y1": 150, "y2": 165, "label": "Z3", "hue": 80 }]',
  "}",
  "```",
  "",
  "### Stacked",
  "Set `stacked: true` on the chart for stacked bar/area charts. Override per-series with `stackId` if you need multiple stacks.",
  "",
  "### Tick / tooltip formatters",
  "Set `format` on `xAxis`, `yAxis`, or `tooltip`. All locale-sensitive output is forced to `en-US`.",
  "",
  "- `default` — numbers via `toLocaleString`, strings pass through.",
  "- `pace` — `270` → `4:30/km`. Pair with `yAxis.reversed: true` for pace charts.",
  "- `duration` — `3600` → `1:00:00`, `90` → `1:30`.",
  "- `hr` — `150` → `150 bpm`.",
  "- `distance` — `5000` → `5.0 km`, `400` → `400 m`.",
  '- `percent` — `0.5` → `50%`. Use `{ "format": "percent", "scale": "whole" }` if your numbers are already 0–100.',
  '- Template strings with a single `{value}` placeholder for one-offs, e.g. `"{value} W"`, `"{value} kJ"`.',
  "",
  "### Other notes",
  "- Animations are disabled — don't bother with animation-related fields.",
  '- Set `legend: false` to hide the legend; `"top"` or `"bottom"` to position it.',
  "- Set `tooltip: false` to disable the tooltip.",
  "- Charts with malformed JSON or unknown `type` render an `Invalid Chart` notice. Schema is **not** validated server-side — keep the shape close to the examples above.",
  "",
  "## Icons",
  "Three icon formats are supported (in order of preference):",
  "1. **Tabler icon name** — a plain string like `run` or `bike`. This is the preferred format. Use `search_icons` to discover available names.",
  "2. **Emoji** — a single emoji character like 🏃 or 🏊",
  "3. **Raw SVG** — a string starting with `<svg` (rendered inline as-is)",
  "",
  "Common Tabler icon suggestions:",
  "- `run` — running",
  "- `bike` — cycling",
  "- `swimming` — swimming",
  "- `barbell` — weight training",
  "- `yoga` — yoga / flexibility",
  "- `stretching` — mobility / stretching",
  "- `walk` — walking",
  "- `trekking` — trail running / hiking",
  "- `trophy` — race day / competitions",
  "- `bed` — rest / recovery",
  "- `heartbeat` — heart rate / cardio",
  "- `bolt` — speed / power",
  "",
  "## Metadata shapes",
  "",
  "### workout metadata",
  "```ts",
  "{",
  "  optional?: boolean,",
  "  ui?: {",
  "    variant?: 'standard' | 'rest' | 'note'",
  "  },",
  "  intervals?: Array<...>,",
  "  zones?: Array<...>,",
  "  sets?: Array<...>,",
  "  segments?: Array<...>,",
  "  [key: string]: unknown",
  "}",
  "```",
  "",
  "### execution",
  "The full schema for `execution` lives on the `add_workouts` / `update_workouts` tool inputs. This guide covers conventions and examples; the tool input schema is authoritative.",
  "- **Use version 2** — set `version: 2`.",
  "- **Use `alert`, not `cue`** — only the documented v2 block and alert fields are supported.",
  "- Supported block types: `warmup`, `cooldown`, `steady`, `rest`, `free`, `interval`, `repeat`.",
  "- Unsupported in `execution`: `strength`, `note`, `lap-button`, `poolLengthMeters`, `displayHints`, and `appleWatch.alerts`.",
  "- If no exact example below fits the workout cleanly, omit `execution` rather than guessing.",
  "",
  "```ts",
  "{",
  "  version: 2,",
  "  structure: [",
  "    { type: 'warmup', target: { type: 'time', seconds: 600 } },",
  "    {",
  "      type: 'interval',",
  "      repetitions: 4,",
  "      work: {",
  "        target: { type: 'distance', meters: 1000 },",
  "        alert: { type: 'paceRange', unit: 'min/km', min: '4:50', max: '5:10' }",
  "      },",
  "      recovery: { target: { type: 'time', seconds: 90 } }",
  "    },",
  "    { type: 'cooldown', target: { type: 'time', seconds: 300 } }",
  "  ],",
  "  appleWatch: { activityType: 'running', location: 'outdoor' }",
  "}",
  "```",
  "",
  "### Copyable v2 examples",
  "",
  "**Steady run with a heart-rate alert**",
  "",
  "```json",
  "{",
  '  "version": 2,',
  '  "structure": [',
  "    {",
  '      "type": "steady",',
  '      "displayName": "Easy aerobic run",',
  '      "target": { "type": "distance", "meters": 5000 },',
  '      "alert": { "type": "heartRateZone", "zone": 2 }',
  "    }",
  "  ],",
  '  "appleWatch": { "activityType": "running", "location": "outdoor" }',
  "}",
  "```",
  "",
  "**Interval run with a pace range**",
  "",
  "```json",
  "{",
  '  "version": 2,',
  '  "structure": [',
  '    { "type": "warmup", "target": { "type": "time", "seconds": 900 } },',
  "    {",
  '      "type": "interval",',
  '      "repetitions": 4,',
  '      "work": {',
  '        "target": { "type": "distance", "meters": 1000 },',
  '        "alert": { "type": "paceRange", "unit": "min/km", "min": "4:50", "max": "5:10" }',
  "      },",
  '      "recovery": { "target": { "type": "time", "seconds": 90 } }',
  "    },",
  '    { "type": "cooldown", "target": { "type": "time", "seconds": 600 } }',
  "  ],",
  '  "appleWatch": { "activityType": "running", "location": "outdoor" }',
  "}",
  "```",
  "",
  "**Swim session using `repeat`**",
  "",
  "```json",
  "{",
  '  "version": 2,',
  '  "structure": [',
  '    { "type": "warmup", "target": { "type": "distance", "meters": 200 } },',
  "    {",
  '      "type": "repeat",',
  '      "repetitions": 4,',
  '      "blocks": [',
  '        { "type": "steady", "displayName": "Freestyle drill", "target": { "type": "distance", "meters": 50 } },',
  '        { "type": "rest", "target": { "type": "time", "seconds": 20 } }',
  "      ]",
  "    },",
  "    {",
  '      "type": "repeat",',
  '      "repetitions": 3,',
  '      "blocks": [',
  '        { "type": "steady", "displayName": "Main set", "target": { "type": "distance", "meters": 100 } },',
  '        { "type": "rest", "target": { "type": "time", "seconds": 30 } }',
  "      ]",
  "    },",
  '    { "type": "cooldown", "target": { "type": "distance", "meters": 100 } }',
  "  ],",
  '  "appleWatch": { "activityType": "swimming", "location": "indoor" }',
  "}",
  "```",
  "",
  "**Bike workout using power alerts**",
  "",
  "```json",
  "{",
  '  "version": 2,',
  '  "structure": [',
  '    { "type": "warmup", "target": { "type": "time", "seconds": 900 } },',
  "    {",
  '      "type": "interval",',
  '      "repetitions": 3,',
  '      "work": {',
  '        "target": { "type": "time", "seconds": 600 },',
  '        "alert": { "type": "powerThreshold", "threshold": 250, "metric": "average" }',
  "      },",
  '      "recovery": { "target": { "type": "time", "seconds": 300 } }',
  "    },",
  '    { "type": "cooldown", "target": { "type": "time", "seconds": 600 } }',
  "  ],",
  '  "appleWatch": { "activityType": "cycling", "location": "outdoor" }',
  "}",
  "```",
  "",
  "**Full `update_workouts` payload replacing execution**",
  "",
  "```json",
  "{",
  '  "updates": [',
  "    {",
  '      "workoutId": "00000000-0000-4000-8000-000000000000",',
  '      "execution": {',
  '        "version": 2,',
  '        "structure": [',
  '          { "type": "steady", "target": { "type": "distance", "meters": 5000 }, "alert": { "type": "heartRateZone", "zone": 2 } }',
  "        ],",
  '        "appleWatch": { "activityType": "running", "location": "outdoor" }',
  "      }",
  "    }",
  "  ]",
  "}",
  "```",
  "",
  "`update_workouts` replaces each item's `execution` with the full object you send for that update. Omitting `execution` leaves it unchanged. Sending `execution: null` clears it. Pass multiple items in `updates` to apply many edits in one call (e.g. rescheduling a week).",
  "",
  "## Conventions",
  '- **Pace** — use `M:SS` strings for `min/km` and `min/mi` (e.g. `"4:50"`); use positive numbers for `km/h` and `mph`. Use `paceRange` for bounded targets and `paceThreshold` for one-sided / single-value targets. For time-based pace ranges, `min` is the faster bound and `max` is the slower bound.',
  '- **Heart rate** — use exactly one alert per step. Prefer `heartRateZone` (`{ type: "heartRateZone", zone: 2 }`). Use `heartRateRange` only for bespoke BPM windows (`{ type: "heartRateRange", min: 131, max: 162 }`).',
  "- **Single alert per step** — do not combine pace + heart rate + power + cadence on the same step. Pick the one most important watch alert for that phase.",
].join("\n");
