import type { Label, PlanNote as PlanNoteType, Workout } from "../../../lib/types.ts";

const TS = "2026-01-01T00:00:00Z";

export const SAMPLE_LABELS: Label[] = [
  { id: "label-run", key: "easy-run", label: "Easy Run", hue: 150, icon: "run", metadata: null, activitySports: ["Run", "TrailRun", "VirtualRun"], createdAt: TS, updatedAt: TS },
  { id: "label-bike", key: "bike", label: "Bike", hue: 250, icon: "bike", metadata: null, activitySports: ["Ride", "GravelRide"], createdAt: TS, updatedAt: TS },
  {
    id: "label-strength",
    key: "strength",
    label: "Strength",
    hue: 30,
    icon: "strength",
    metadata: null,
    activitySports: ["WeightTraining", "Workout"],
    createdAt: TS,
    updatedAt: TS,
  },
  { id: "label-rest", key: "rest", label: "Rest", hue: 0, icon: "rest", metadata: null, activitySports: [], createdAt: TS, updatedAt: TS },
];

export const SAMPLE_WORKOUTS: (Workout & { dateLabel: string })[] = [
  {
    id: "w1",
    planId: "plan-1",
    phaseId: null,
    date: "2026-04-06",
    labelId: "label-run",
    label: SAMPLE_LABELS[0],
    title: "Easy Recovery Run",
    description:
      "Easy pace run to recover from the weekend. Keep heart rate in **Zone 2** throughout.\n\n### Execution\n- Warm up: 10 min walk/jog\n- Main: 30 min easy\n- Cool down: 5 min walk\n\n> Focus on nasal breathing and relaxed shoulders.",
    targetDurationMin: 45,
    targetDistanceM: null,
    sortOrder: 0,
    status: "planned",
    completionNotes: null,
    trainerNotes: "Great week ahead. Start easy, save energy for Thursday's intervals.",
    activity: null,
    execution: {
      version: 2,
      structure: [{ type: "steady", target: { type: "time", seconds: 2700 }, alert: { type: "heartRateZone", zone: 2 } }],
      appleWatch: { activityType: "running", location: "outdoor" },
    },
    metadata: null,
    createdAt: TS,
    updatedAt: TS,
    dateLabel: "Mon",
  },
  {
    id: "w2",
    planId: "plan-1",
    phaseId: null,
    date: "2026-04-07",
    labelId: "label-strength",
    label: SAMPLE_LABELS[2],
    title: "Upper Body + Core",
    description:
      "Full upper body session with Marek.\n\n| Exercise | Sets | Reps |\n|---|---|---|\n| Bench Press | 4 | 8 |\n| Pull-ups | 4 | 10 |\n| OHP | 3 | 10 |\n| Plank | 3 | 60s |",
    targetDurationMin: 60,
    targetDistanceM: null,
    sortOrder: 0,
    status: "completed",
    completionNotes: null,
    trainerNotes: null,
    activity: {
      stravaId: 12345,
      sport: "WeightTraining",
      name: "Sample upper body",
      startDate: "2026-04-07T08:00:00Z",
      timezone: null,
      durationSec: 3600,
      distanceM: null,
      elevationM: null,
      avgHr: null,
      maxHr: null,
      avgPower: null,
      calories: null,
    },
    execution: null,
    metadata: null,
    createdAt: TS,
    updatedAt: TS,
    dateLabel: "Tue",
  },
  {
    id: "w3",
    planId: "plan-1",
    phaseId: null,
    date: "2026-04-08",
    labelId: "label-bike",
    label: SAMPLE_LABELS[1],
    title: "Sweet Spot Intervals",
    description: "Bike sweet spot session on the trainer.\n\n- 15 min warm-up spinning\n- 4 × 8 min @ 88–93% FTP, 4 min recovery\n- 10 min cool down\n\nTotal target: ~75 min",
    targetDurationMin: 75,
    targetDistanceM: null,
    sortOrder: 0,
    status: "planned",
    completionNotes: null,
    trainerNotes: null,
    activity: null,
    execution: {
      version: 2,
      structure: [
        { type: "warmup", target: { type: "time", seconds: 900 }, displayName: "Warm-up" },
        {
          type: "interval",
          repetitions: 4,
          work: { target: { type: "time", seconds: 480 }, displayName: "Sweet spot" },
          recovery: { target: { type: "time", seconds: 240 }, displayName: "Recovery" },
        },
        { type: "cooldown", target: { type: "time", seconds: 600 }, displayName: "Cool down" },
      ],
      appleWatch: { activityType: "cycling", location: "indoor" },
    },
    metadata: { optional: true },
    createdAt: TS,
    updatedAt: TS,
    dateLabel: "Wed",
  },
  {
    id: "w4",
    planId: "plan-1",
    phaseId: null,
    date: "2026-04-09",
    labelId: "label-rest",
    label: SAMPLE_LABELS[3],
    title: "Rest Day",
    description: "Full rest. Light stretching if needed.",
    targetDurationMin: null,
    targetDistanceM: null,
    sortOrder: 0,
    status: "planned",
    completionNotes: null,
    trainerNotes: null,
    activity: null,
    execution: null,
    metadata: { ui: { variant: "rest" as const } },
    createdAt: TS,
    updatedAt: TS,
    dateLabel: "Thu",
  },
  {
    id: "w5",
    planId: "plan-1",
    phaseId: null,
    date: "2026-04-10",
    labelId: "label-run",
    label: SAMPLE_LABELS[0],
    title: "Track Intervals",
    description:
      "Speed session at the track.\n\n### Warm-up\n2 km easy + dynamic stretching + 4 × 100m strides\n\n### Main Set\n6 × 800m @ 5K pace, 400m jog recovery\n\n### Cool-down\n2 km easy jog\n\n---\n\n*Target 800m pace: 3:15–3:20*",
    targetDurationMin: 60,
    targetDistanceM: 12000,
    sortOrder: 0,
    status: "planned",
    completionNotes: null,
    trainerNotes: null,
    activity: null,
    execution: null,
    metadata: null,
    createdAt: TS,
    updatedAt: TS,
    dateLabel: "Fri",
  },
  {
    id: "w-note",
    planId: "plan-1",
    phaseId: null,
    date: "2026-04-10",
    labelId: "label-run",
    label: SAMPLE_LABELS[0],
    title: "Weekly Reflection",
    description: "Take a moment to reflect on this week's training. How did the intervals feel? Any niggles or fatigue to note?",
    targetDurationMin: null,
    targetDistanceM: null,
    sortOrder: 1,
    status: "planned",
    completionNotes: null,
    trainerNotes: null,
    activity: null,
    execution: null,
    metadata: { ui: { variant: "note" as const } },
    createdAt: TS,
    updatedAt: TS,
    dateLabel: "",
  },
];

export const SAMPLE_NOTE: PlanNoteType = {
  id: "pn1",
  planId: "plan-1",
  type: "summary",
  content:
    "**Week 8 — Race-simulation week.** Focus on race-pace efforts and mental rehearsal. Keep Tuesday easy, nail Thursday's brick session. Weekend long run is the key session.\n\nHydration target: 500ml/hr during sessions over 60 min.",
  metadata: { week: 8 },
  createdAt: "2026-04-04T10:00:00Z",
  updatedAt: "2026-04-04T10:00:00Z",
};
