/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as DevDesignSystemRouteImport } from './routes/dev/design-system'
import { Route as DevDesignSystemIndexRouteImport } from './routes/dev/design-system/index'
import { Route as DevDesignSystemTokensRouteImport } from './routes/dev/design-system/tokens'
import { Route as DevDesignSystemToastsRouteImport } from './routes/dev/design-system/toasts'
import { Route as DevDesignSystemPrimitivesRouteImport } from './routes/dev/design-system/primitives'
import { Route as DevDesignSystemMarkdownRouteImport } from './routes/dev/design-system/markdown'
import { Route as DevDesignSystemDomainRouteImport } from './routes/dev/design-system/domain'
import { Route as DevDesignSystemCrossfadeRouteImport } from './routes/dev/design-system/crossfade'
import { Route as DevDesignSystemCompositesRouteImport } from './routes/dev/design-system/composites'
import { Route as DevDesignSystemColorsRouteImport } from './routes/dev/design-system/colors'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemIndexRoute = DevDesignSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemTokensRoute = DevDesignSystemTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemToastsRoute = DevDesignSystemToastsRouteImport.update({
  id: '/toasts',
  path: '/toasts',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemPrimitivesRoute =
  DevDesignSystemPrimitivesRouteImport.update({
    id: '/primitives',
    path: '/primitives',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemMarkdownRoute = DevDesignSystemMarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemDomainRoute = DevDesignSystemDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemCrossfadeRoute =
  DevDesignSystemCrossfadeRouteImport.update({
    id: '/crossfade',
    path: '/crossfade',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemCompositesRoute =
  DevDesignSystemCompositesRouteImport.update({
    id: '/composites',
    path: '/composites',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemColorsRoute = DevDesignSystemColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DevDesignSystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/design-system': typeof DevDesignSystemRouteWithChildren
  '/share/$shareId': typeof ShareShareIdRoute
  '/dev/design-system/colors': typeof DevDesignSystemColorsRoute
  '/dev/design-system/composites': typeof DevDesignSystemCompositesRoute
  '/dev/design-system/crossfade': typeof DevDesignSystemCrossfadeRoute
  '/dev/design-system/domain': typeof DevDesignSystemDomainRoute
  '/dev/design-system/markdown': typeof DevDesignSystemMarkdownRoute
  '/dev/design-system/primitives': typeof DevDesignSystemPrimitivesRoute
  '/dev/design-system/toasts': typeof DevDesignSystemToastsRoute
  '/dev/design-system/tokens': typeof DevDesignSystemTokensRoute
  '/dev/design-system/': typeof DevDesignSystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/dev/design-system/colors': typeof DevDesignSystemColorsRoute
  '/dev/design-system/composites': typeof DevDesignSystemCompositesRoute
  '/dev/design-system/crossfade': typeof DevDesignSystemCrossfadeRoute
  '/dev/design-system/domain': typeof DevDesignSystemDomainRoute
  '/dev/design-system/markdown': typeof DevDesignSystemMarkdownRoute
  '/dev/design-system/primitives': typeof DevDesignSystemPrimitivesRoute
  '/dev/design-system/toasts': typeof DevDesignSystemToastsRoute
  '/dev/design-system/tokens': typeof DevDesignSystemTokensRoute
  '/dev/design-system': typeof DevDesignSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/design-system': typeof DevDesignSystemRouteWithChildren
  '/share/$shareId': typeof ShareShareIdRoute
  '/dev/design-system/colors': typeof DevDesignSystemColorsRoute
  '/dev/design-system/composites': typeof DevDesignSystemCompositesRoute
  '/dev/design-system/crossfade': typeof DevDesignSystemCrossfadeRoute
  '/dev/design-system/domain': typeof DevDesignSystemDomainRoute
  '/dev/design-system/markdown': typeof DevDesignSystemMarkdownRoute
  '/dev/design-system/primitives': typeof DevDesignSystemPrimitivesRoute
  '/dev/design-system/toasts': typeof DevDesignSystemToastsRoute
  '/dev/design-system/tokens': typeof DevDesignSystemTokensRoute
  '/dev/design-system/': typeof DevDesignSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dev/design-system'
    | '/share/$shareId'
    | '/dev/design-system/colors'
    | '/dev/design-system/composites'
    | '/dev/design-system/crossfade'
    | '/dev/design-system/domain'
    | '/dev/design-system/markdown'
    | '/dev/design-system/primitives'
    | '/dev/design-system/toasts'
    | '/dev/design-system/tokens'
    | '/dev/design-system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/share/$shareId'
    | '/dev/design-system/colors'
    | '/dev/design-system/composites'
    | '/dev/design-system/crossfade'
    | '/dev/design-system/domain'
    | '/dev/design-system/markdown'
    | '/dev/design-system/primitives'
    | '/dev/design-system/toasts'
    | '/dev/design-system/tokens'
    | '/dev/design-system'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/dev/design-system'
    | '/share/$shareId'
    | '/dev/design-system/colors'
    | '/dev/design-system/composites'
    | '/dev/design-system/crossfade'
    | '/dev/design-system/domain'
    | '/dev/design-system/markdown'
    | '/dev/design-system/primitives'
    | '/dev/design-system/toasts'
    | '/dev/design-system/tokens'
    | '/dev/design-system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DevDesignSystemRoute: typeof DevDesignSystemRouteWithChildren
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system/': {
      id: '/dev/design-system/'
      path: '/'
      fullPath: '/dev/design-system/'
      preLoaderRoute: typeof DevDesignSystemIndexRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/tokens': {
      id: '/dev/design-system/tokens'
      path: '/tokens'
      fullPath: '/dev/design-system/tokens'
      preLoaderRoute: typeof DevDesignSystemTokensRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/toasts': {
      id: '/dev/design-system/toasts'
      path: '/toasts'
      fullPath: '/dev/design-system/toasts'
      preLoaderRoute: typeof DevDesignSystemToastsRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/primitives': {
      id: '/dev/design-system/primitives'
      path: '/primitives'
      fullPath: '/dev/design-system/primitives'
      preLoaderRoute: typeof DevDesignSystemPrimitivesRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/markdown': {
      id: '/dev/design-system/markdown'
      path: '/markdown'
      fullPath: '/dev/design-system/markdown'
      preLoaderRoute: typeof DevDesignSystemMarkdownRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/domain': {
      id: '/dev/design-system/domain'
      path: '/domain'
      fullPath: '/dev/design-system/domain'
      preLoaderRoute: typeof DevDesignSystemDomainRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/crossfade': {
      id: '/dev/design-system/crossfade'
      path: '/crossfade'
      fullPath: '/dev/design-system/crossfade'
      preLoaderRoute: typeof DevDesignSystemCrossfadeRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/composites': {
      id: '/dev/design-system/composites'
      path: '/composites'
      fullPath: '/dev/design-system/composites'
      preLoaderRoute: typeof DevDesignSystemCompositesRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/colors': {
      id: '/dev/design-system/colors'
      path: '/colors'
      fullPath: '/dev/design-system/colors'
      preLoaderRoute: typeof DevDesignSystemColorsRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
  }
}

interface DevDesignSystemRouteChildren {
  DevDesignSystemColorsRoute: typeof DevDesignSystemColorsRoute
  DevDesignSystemCompositesRoute: typeof DevDesignSystemCompositesRoute
  DevDesignSystemCrossfadeRoute: typeof DevDesignSystemCrossfadeRoute
  DevDesignSystemDomainRoute: typeof DevDesignSystemDomainRoute
  DevDesignSystemMarkdownRoute: typeof DevDesignSystemMarkdownRoute
  DevDesignSystemPrimitivesRoute: typeof DevDesignSystemPrimitivesRoute
  DevDesignSystemToastsRoute: typeof DevDesignSystemToastsRoute
  DevDesignSystemTokensRoute: typeof DevDesignSystemTokensRoute
  DevDesignSystemIndexRoute: typeof DevDesignSystemIndexRoute
}

const DevDesignSystemRouteChildren: DevDesignSystemRouteChildren = {
  DevDesignSystemColorsRoute: DevDesignSystemColorsRoute,
  DevDesignSystemCompositesRoute: DevDesignSystemCompositesRoute,
  DevDesignSystemCrossfadeRoute: DevDesignSystemCrossfadeRoute,
  DevDesignSystemDomainRoute: DevDesignSystemDomainRoute,
  DevDesignSystemMarkdownRoute: DevDesignSystemMarkdownRoute,
  DevDesignSystemPrimitivesRoute: DevDesignSystemPrimitivesRoute,
  DevDesignSystemToastsRoute: DevDesignSystemToastsRoute,
  DevDesignSystemTokensRoute: DevDesignSystemTokensRoute,
  DevDesignSystemIndexRoute: DevDesignSystemIndexRoute,
}

const DevDesignSystemRouteWithChildren = DevDesignSystemRoute._addFileChildren(
  DevDesignSystemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DevDesignSystemRoute: DevDesignSystemRouteWithChildren,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
