/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as DevDesignSystemRouteImport } from './routes/dev/design-system'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as DevDesignSystemIndexRouteImport } from './routes/dev/design-system/index'
import { Route as DevDesignSystemWorkoutCardRouteImport } from './routes/dev/design-system/workout-card'
import { Route as DevDesignSystemTooltipRouteImport } from './routes/dev/design-system/tooltip'
import { Route as DevDesignSystemTokensRouteImport } from './routes/dev/design-system/tokens'
import { Route as DevDesignSystemToastsRouteImport } from './routes/dev/design-system/toasts'
import { Route as DevDesignSystemPrimitivesRouteImport } from './routes/dev/design-system/primitives'
import { Route as DevDesignSystemMarkdownRouteImport } from './routes/dev/design-system/markdown'
import { Route as DevDesignSystemDomainRouteImport } from './routes/dev/design-system/domain'
import { Route as DevDesignSystemCrossfadeRouteImport } from './routes/dev/design-system/crossfade'
import { Route as DevDesignSystemCompositesRouteImport } from './routes/dev/design-system/composites'
import { Route as DevDesignSystemColorsRouteImport } from './routes/dev/design-system/colors'
import { Route as DevDesignSystemChartsRouteImport } from './routes/dev/design-system/charts'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const DevDesignSystemIndexRoute = DevDesignSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemWorkoutCardRoute =
  DevDesignSystemWorkoutCardRouteImport.update({
    id: '/workout-card',
    path: '/workout-card',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemTooltipRoute = DevDesignSystemTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemTokensRoute = DevDesignSystemTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemToastsRoute = DevDesignSystemToastsRouteImport.update({
  id: '/toasts',
  path: '/toasts',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemPrimitivesRoute =
  DevDesignSystemPrimitivesRouteImport.update({
    id: '/primitives',
    path: '/primitives',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemMarkdownRoute = DevDesignSystemMarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemDomainRoute = DevDesignSystemDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemCrossfadeRoute =
  DevDesignSystemCrossfadeRouteImport.update({
    id: '/crossfade',
    path: '/crossfade',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemCompositesRoute =
  DevDesignSystemCompositesRouteImport.update({
    id: '/composites',
    path: '/composites',
    getParentRoute: () => DevDesignSystemRoute,
  } as any)
const DevDesignSystemColorsRoute = DevDesignSystemColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DevDesignSystemRoute,
} as any)
const DevDesignSystemChartsRoute = DevDesignSystemChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => DevDesignSystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/help': typeof HelpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/login': typeof AppLoginRoute
  '/settings': typeof AppSettingsRoute
  '/signup': typeof AppSignupRoute
  '/dev/design-system': typeof DevDesignSystemRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/dev/design-system/charts': typeof DevDesignSystemChartsRoute
  '/dev/design-system/colors': typeof DevDesignSystemColorsRoute
  '/dev/design-system/composites': typeof DevDesignSystemCompositesRoute
  '/dev/design-system/crossfade': typeof DevDesignSystemCrossfadeRoute
  '/dev/design-system/domain': typeof DevDesignSystemDomainRoute
  '/dev/design-system/markdown': typeof DevDesignSystemMarkdownRoute
  '/dev/design-system/primitives': typeof DevDesignSystemPrimitivesRoute
  '/dev/design-system/toasts': typeof DevDesignSystemToastsRoute
  '/dev/design-system/tokens': typeof DevDesignSystemTokensRoute
  '/dev/design-system/tooltip': typeof DevDesignSystemTooltipRoute
  '/dev/design-system/workout-card': typeof DevDesignSystemWorkoutCardRoute
  '/dev/design-system/': typeof DevDesignSystemIndexRoute
}
export interface FileRoutesByTo {
  '/help': typeof HelpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/login': typeof AppLoginRoute
  '/settings': typeof AppSettingsRoute
  '/signup': typeof AppSignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/': typeof AppIndexRoute
  '/dev/design-system/charts': typeof DevDesignSystemChartsRoute
  '/dev/design-system/colors': typeof DevDesignSystemColorsRoute
  '/dev/design-system/composites': typeof DevDesignSystemCompositesRoute
  '/dev/design-system/crossfade': typeof DevDesignSystemCrossfadeRoute
  '/dev/design-system/domain': typeof DevDesignSystemDomainRoute
  '/dev/design-system/markdown': typeof DevDesignSystemMarkdownRoute
  '/dev/design-system/primitives': typeof DevDesignSystemPrimitivesRoute
  '/dev/design-system/toasts': typeof DevDesignSystemToastsRoute
  '/dev/design-system/tokens': typeof DevDesignSystemTokensRoute
  '/dev/design-system/tooltip': typeof DevDesignSystemTooltipRoute
  '/dev/design-system/workout-card': typeof DevDesignSystemWorkoutCardRoute
  '/dev/design-system': typeof DevDesignSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signup': typeof AppSignupRoute
  '/dev/design-system': typeof DevDesignSystemRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/_app/': typeof AppIndexRoute
  '/dev/design-system/charts': typeof DevDesignSystemChartsRoute
  '/dev/design-system/colors': typeof DevDesignSystemColorsRoute
  '/dev/design-system/composites': typeof DevDesignSystemCompositesRoute
  '/dev/design-system/crossfade': typeof DevDesignSystemCrossfadeRoute
  '/dev/design-system/domain': typeof DevDesignSystemDomainRoute
  '/dev/design-system/markdown': typeof DevDesignSystemMarkdownRoute
  '/dev/design-system/primitives': typeof DevDesignSystemPrimitivesRoute
  '/dev/design-system/toasts': typeof DevDesignSystemToastsRoute
  '/dev/design-system/tokens': typeof DevDesignSystemTokensRoute
  '/dev/design-system/tooltip': typeof DevDesignSystemTooltipRoute
  '/dev/design-system/workout-card': typeof DevDesignSystemWorkoutCardRoute
  '/dev/design-system/': typeof DevDesignSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/privacy-policy'
    | '/login'
    | '/settings'
    | '/signup'
    | '/dev/design-system'
    | '/oauth/consent'
    | '/share/$shareId'
    | '/dev/design-system/charts'
    | '/dev/design-system/colors'
    | '/dev/design-system/composites'
    | '/dev/design-system/crossfade'
    | '/dev/design-system/domain'
    | '/dev/design-system/markdown'
    | '/dev/design-system/primitives'
    | '/dev/design-system/toasts'
    | '/dev/design-system/tokens'
    | '/dev/design-system/tooltip'
    | '/dev/design-system/workout-card'
    | '/dev/design-system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/help'
    | '/privacy-policy'
    | '/login'
    | '/settings'
    | '/signup'
    | '/oauth/consent'
    | '/share/$shareId'
    | '/'
    | '/dev/design-system/charts'
    | '/dev/design-system/colors'
    | '/dev/design-system/composites'
    | '/dev/design-system/crossfade'
    | '/dev/design-system/domain'
    | '/dev/design-system/markdown'
    | '/dev/design-system/primitives'
    | '/dev/design-system/toasts'
    | '/dev/design-system/tokens'
    | '/dev/design-system/tooltip'
    | '/dev/design-system/workout-card'
    | '/dev/design-system'
  id:
    | '__root__'
    | '/_app'
    | '/help'
    | '/privacy-policy'
    | '/_app/login'
    | '/_app/settings'
    | '/_app/signup'
    | '/dev/design-system'
    | '/oauth/consent'
    | '/share/$shareId'
    | '/_app/'
    | '/dev/design-system/charts'
    | '/dev/design-system/colors'
    | '/dev/design-system/composites'
    | '/dev/design-system/crossfade'
    | '/dev/design-system/domain'
    | '/dev/design-system/markdown'
    | '/dev/design-system/primitives'
    | '/dev/design-system/toasts'
    | '/dev/design-system/tokens'
    | '/dev/design-system/tooltip'
    | '/dev/design-system/workout-card'
    | '/dev/design-system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  DevDesignSystemRoute: typeof DevDesignSystemRouteWithChildren
  OauthConsentRoute: typeof OauthConsentRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/design-system/': {
      id: '/dev/design-system/'
      path: '/'
      fullPath: '/dev/design-system/'
      preLoaderRoute: typeof DevDesignSystemIndexRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/workout-card': {
      id: '/dev/design-system/workout-card'
      path: '/workout-card'
      fullPath: '/dev/design-system/workout-card'
      preLoaderRoute: typeof DevDesignSystemWorkoutCardRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/tooltip': {
      id: '/dev/design-system/tooltip'
      path: '/tooltip'
      fullPath: '/dev/design-system/tooltip'
      preLoaderRoute: typeof DevDesignSystemTooltipRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/tokens': {
      id: '/dev/design-system/tokens'
      path: '/tokens'
      fullPath: '/dev/design-system/tokens'
      preLoaderRoute: typeof DevDesignSystemTokensRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/toasts': {
      id: '/dev/design-system/toasts'
      path: '/toasts'
      fullPath: '/dev/design-system/toasts'
      preLoaderRoute: typeof DevDesignSystemToastsRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/primitives': {
      id: '/dev/design-system/primitives'
      path: '/primitives'
      fullPath: '/dev/design-system/primitives'
      preLoaderRoute: typeof DevDesignSystemPrimitivesRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/markdown': {
      id: '/dev/design-system/markdown'
      path: '/markdown'
      fullPath: '/dev/design-system/markdown'
      preLoaderRoute: typeof DevDesignSystemMarkdownRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/domain': {
      id: '/dev/design-system/domain'
      path: '/domain'
      fullPath: '/dev/design-system/domain'
      preLoaderRoute: typeof DevDesignSystemDomainRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/crossfade': {
      id: '/dev/design-system/crossfade'
      path: '/crossfade'
      fullPath: '/dev/design-system/crossfade'
      preLoaderRoute: typeof DevDesignSystemCrossfadeRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/composites': {
      id: '/dev/design-system/composites'
      path: '/composites'
      fullPath: '/dev/design-system/composites'
      preLoaderRoute: typeof DevDesignSystemCompositesRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/colors': {
      id: '/dev/design-system/colors'
      path: '/colors'
      fullPath: '/dev/design-system/colors'
      preLoaderRoute: typeof DevDesignSystemColorsRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
    '/dev/design-system/charts': {
      id: '/dev/design-system/charts'
      path: '/charts'
      fullPath: '/dev/design-system/charts'
      preLoaderRoute: typeof DevDesignSystemChartsRouteImport
      parentRoute: typeof DevDesignSystemRoute
    }
  }
}

interface AppRouteChildren {
  AppLoginRoute: typeof AppLoginRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLoginRoute: AppLoginRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DevDesignSystemRouteChildren {
  DevDesignSystemChartsRoute: typeof DevDesignSystemChartsRoute
  DevDesignSystemColorsRoute: typeof DevDesignSystemColorsRoute
  DevDesignSystemCompositesRoute: typeof DevDesignSystemCompositesRoute
  DevDesignSystemCrossfadeRoute: typeof DevDesignSystemCrossfadeRoute
  DevDesignSystemDomainRoute: typeof DevDesignSystemDomainRoute
  DevDesignSystemMarkdownRoute: typeof DevDesignSystemMarkdownRoute
  DevDesignSystemPrimitivesRoute: typeof DevDesignSystemPrimitivesRoute
  DevDesignSystemToastsRoute: typeof DevDesignSystemToastsRoute
  DevDesignSystemTokensRoute: typeof DevDesignSystemTokensRoute
  DevDesignSystemTooltipRoute: typeof DevDesignSystemTooltipRoute
  DevDesignSystemWorkoutCardRoute: typeof DevDesignSystemWorkoutCardRoute
  DevDesignSystemIndexRoute: typeof DevDesignSystemIndexRoute
}

const DevDesignSystemRouteChildren: DevDesignSystemRouteChildren = {
  DevDesignSystemChartsRoute: DevDesignSystemChartsRoute,
  DevDesignSystemColorsRoute: DevDesignSystemColorsRoute,
  DevDesignSystemCompositesRoute: DevDesignSystemCompositesRoute,
  DevDesignSystemCrossfadeRoute: DevDesignSystemCrossfadeRoute,
  DevDesignSystemDomainRoute: DevDesignSystemDomainRoute,
  DevDesignSystemMarkdownRoute: DevDesignSystemMarkdownRoute,
  DevDesignSystemPrimitivesRoute: DevDesignSystemPrimitivesRoute,
  DevDesignSystemToastsRoute: DevDesignSystemToastsRoute,
  DevDesignSystemTokensRoute: DevDesignSystemTokensRoute,
  DevDesignSystemTooltipRoute: DevDesignSystemTooltipRoute,
  DevDesignSystemWorkoutCardRoute: DevDesignSystemWorkoutCardRoute,
  DevDesignSystemIndexRoute: DevDesignSystemIndexRoute,
}

const DevDesignSystemRouteWithChildren = DevDesignSystemRoute._addFileChildren(
  DevDesignSystemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  DevDesignSystemRoute: DevDesignSystemRouteWithChildren,
  OauthConsentRoute: OauthConsentRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
